[remote.github]
owner = "zobweyt"
repo = "textcase"

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""

body = """
{%- set remote_url = "https://github.com/" ~ remote.github.owner ~ "/" ~ remote.github.repo -%}
{%- set new_contributors = github.contributors | filter(attribute="is_first_time", value=true) -%}

{% if version %}
    {% if previous.version -%}
        ## [{{ version }}]({{ remote_url }}/compare/{{ previous.version }}...{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
    {% else -%}
        ## [{{ version }}]({{ remote_url }}/commits/{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
    {% endif -%}
{% else -%}
    ## Unreleased
{% endif -%}

{% if message %}
    {{ message }}
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }} <!-- omit in toc -->
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | trim }} ([`{{ commit.id | truncate(length=7, end="") }}`]({{ remote_url }}/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor -%}

{% if new_contributors %}
    #### New Contributors <!-- omit in toc -->
    {% for contributor in new_contributors %}
        - [@{{ contributor.username }}](https://github.com/{{ contributor.username }}) made their first contribution{% if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ remote_url }}/pull/{{ contributor.pr_number }}){% endif %}\
    {% endfor %}
{% endif -%}
"""

[git]
commit_parsers = [
    { message = "^doc|^style|^chore|^ci", skip = true },
    { message = "^fix", group = "<!-- 0 -->Bug Fixes" },
    { message = "^feat", group = "<!-- 1 -->Features" },
    { message = "^perf", group = "<!-- 2 -->Performance" },
    { message = "^refactor", group = "<!-- 3 -->Refactoring" },
    { message = "^test", group = "<!-- 4 -->Testing" },
]
conventional_commits = true
filter_commits = false
filter_unconventional = false
sort_commits = "oldest"
topo_order = false
