[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""

body = """
{% if version %}
    {% if previous.version and version %}\
        ## [{{ version }}](https://github.com/zobweyt/textcase/compare/{{ previous.version }}...{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
    {% else %}\
        ## [{{ version }}](https://github.com/zobweyt/textcase/commits/{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
    {% endif %}\
{% else %}\
    ## Unreleased
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }} <!-- omit in toc -->
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | trim }} ([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/zobweyt/textcase/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}
"""

[git]
commit_parsers = [
    { message = "^doc|^style|^chore|^ci", skip = true },
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^test", group = "Testing" },
]
conventional_commits = true
filter_commits = false
filter_unconventional = false
sort_commits = "oldest"
topo_order = false
