site_name: textcase
site_description: A feature-rich Python text case conversion library
site_author: Nikita Gaziev
site_url: https://zobweyt.github.io/textcase/

edit_uri: blob/main/docs/

repo_name: zobweyt/textcase
repo_url: https://github.com/zobweyt/textcase

copyright: Copyright &copy; 2025 Nikita Gaziev

watch:
  - textcase

theme:
  name: material
  logo: assets/favicon.white.svg
  favicon: assets/favicon.svg
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: brown
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  language: en

nav:
  - Home: index.md
  - Learn:
      - learn/boundaries.md
      - learn/cases.md
      - learn/converter.md
  - Reference:
      - reference/boundary.md
      - reference/case.md
      - reference/convert.md
      - reference/converter.md
      - reference/is_case.md
      - reference/pattern.md
  - Changelog: changelog.md

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
      js_files:
      css_files:
  - markdown-exec
  - autorefs:
      resolve_closest: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
          nav_translations:
            Home: Главная
            Learn: Обучение
            Reference: Спецификация
            Changelog: Журнал изменений
  - git-committers:
      repository: zobweyt/textcase
      branch: main
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      type: timeago
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - "!^_"
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: "#"

extra:
  analytics:
    provider: google
    property: G-D2KZPTT9KB
    feedback:
      title: Was this page helpful?
      ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: Thanks for your feedback!
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: Thanks for your feedback!
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/textcase
      name: PyPi
    - icon: fontawesome/brands/github
      link: https://github.com/zobweyt/textcase
      name: GitHub repository
