site_name: textcase
site_description: A feature-rich Python text case conversion library
site_author: Nikita Gaziev
site_url: https://zobweyt.github.io/textcase/
repo_name: zobweyt/textcase
repo_url: https://github.com/zobweyt/textcase
edit_uri: blob/main/docs/
exclude_docs: .*

copyright: Copyright &copy; 2025 Nikita Gaziev

watch:
  - src
  - tests

theme:
  name: material
  icon:
    repo: simple/github
  logo: assets/favicon.white.svg
  favicon: assets/favicon.svg
  language: en
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  custom_dir: docs/.overrides

nav:
  - Home: index.md
  - Learn:
      - learn/boundaries.md
      - learn/cases.md
  - Reference: reference.md
  - Changelog: changelog.md

plugins:
  - search
  - social
  - autorefs:
      resolve_closest: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
          copyright: Авторские права &copy; 2025 Никита Газиев
          site_author: Никита Газиев
          site_description: Многофункциональная библиотека преобразования регистра текста в Python
          nav_translations:
            Home: Главная
            Learn: Обучение
            Reference: Спецификация
            Changelog: Журнал изменений
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            extensions:
              - griffe_typingdoc
            filters:
              - "!^__all__"
            annotations_path: source
            docstring_section_style: spacy
            inherited_members: true
            line_length: 120
            members_order: source
            merge_init_into_class: true
            modernize_annotations: true
            separate_signature: true
            show_if_no_docstring: true
            show_root_heading: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            unwrap_annotated: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: zobweyt/textcase
      branch: main
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
      css_files:

markdown_extensions:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      permalink: "#"
  - abbr
  - attr_list
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      guess_lang: true
      default_lang: python
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences

extra:
  generator: false
  analytics:
    provider: google
    property: G-D2KZPTT9KB
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback!
  social:
    - icon: simple/archlinux
      link: https://aur.archlinux.org/packages/python-textcase-git
      name: AUR
    - icon: simple/pypi
      link: https://pypi.org/project/textcase
      name: PyPI
    - icon: simple/github
      link: https://github.com/zobweyt/textcase
      name: GitHub
