name: coverage

on:
  push:
    branches:
      - main
    paths:
      - src
      - tests
      - justfile
      - uv.lock

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.4

      - name: Run coverage
        run: |
          uv sync
          just coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
