name: coverage

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/coverage.yaml
      - src/**
      - tests/**
      - pyproject.toml
      - uv.lock

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run coverage
        run: uv run task coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
