name: coverage

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/coverage.yaml
      - src/**
      - tests/**
      - justfile
      - pyproject.toml
      - uv.lock

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.6.4

      - name: Run coverage
        run: just coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
