name: docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - docs/**
      - src/**
      - CHANGELOG.md
      - justfile
      - mkdocs.yaml
      - pyproject.toml
      - uv.lock

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            src

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.4

      - name: Deploy docs
        run: just docs-gh-deploy
