name: docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - docs/**
      - src/**
      - pyproject.toml
      - uv.lock

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Deploy docs
        run: uv run task deploy
