name: preview

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/docs.yaml
      - docs/**
      - src/**
      - CHANGELOG.md
      - justfile
      - mkdocs.yaml
      - pyproject.toml
      - uv.lock
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            src

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.4

      - name: Build docs
        run: just docs-build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
