name: test

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/test.yaml
      - src/**
      - tests/**
      - justfile
      - pyproject.toml
      - uv.lock
  pull_request:
    branches-ignore:
      - main
    paths:
      - .github/workflows/test.yaml
      - src/**
      - tests/**
      - justfile
      - pyproject.toml
      - uv.lock

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.4

      - name: Run test
        run: just test
